FROM elixir:1.4.2

COPY docker/sap_global_root_ca.crt docker/SAPNetCA_G2.crt /usr/share/ca-certificates/SAP/
RUN echo "SAP/sap_global_root_ca.crt" >> /etc/ca-certificates.conf && \
    echo "SAP/SAPNetCA_G2.crt" >> /etc/ca-certificates.conf && \
    update-ca-certificates

RUN adduser --disabled-password --gecos '' elixir && \
    wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 && \
    chmod +x /usr/local/bin/dumb-init

ENV PHOENIX_VERSION 1.2.1

RUN mkdir -p /app/current
WORKDIR /app/current
RUN chown -R elixir:elixir /app/current

USER elixir
RUN mix local.hex --force && mix local.rebar --force && mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new-$PHOENIX_VERSION.ez

COPY phoenix/mix.* /app/current/
COPY phoenix/config /app/current/config
RUN rebar3 update && mix deps.get && MIX_ENV=dev mix deps.compile && MIX_ENV=test mix deps.compile

COPY phoenix/lib /app/current/lib
COPY phoenix/priv /app/current/priv
COPY phoenix/test /app/current/test
COPY phoenix/web /app/current/web
COPY phoenix/coveralls.json /app/current/
COPY phoenix/test_tuples.json /app/current/
COPY phoenix/*.pem /app/current/
USER root
RUN chown -R elixir:elixir /app/current
USER elixir
RUN MIX_ENV=dev mix compile && MIX_ENV=test mix compile

ARG PROMPT
RUN [ -n "$PROMPT" ] && echo "PS1=\"[$PROMPT] \$PS1\"" >> ~/.bashrc || true
ARG INFO
RUN [ -n "$INFO" ] && echo "$INFO" > /app/current/build.txt || true

ARG MIX_ENV
EXPOSE 4000
ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
CMD ["mix", "phoenix.server"]